version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: 123qweasd
      MYSQL_DATABASE: express_sequelize
    volumes:
      - express_sequelize:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  express_sequelize:
